"""initial schema

Revision ID: 0001
Revises: 
Create Date: 2026-09-25 17:25:05.106667

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_organizations'))
    )
    op.create_table('permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=64), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_permissions')),
    sa.UniqueConstraint('code', name=op.f('uq_permissions_code'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('invitation_templates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('template_key', sa.String(length=50), nullable=False),
    sa.Column('thumbnail', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), server_default='active', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_invitation_templates_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_invitation_templates'))
    )
    with op.batch_alter_table('invitation_templates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invitation_templates_organization_id'), ['organization_id'], unique=False)

    op.create_table('role_permissions',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('permission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], name=op.f('fk_role_permissions_permission_id_permissions'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id', name=op.f('pk_role_permissions'))
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_users_organization_id_organizations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_users_role_id_roles'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role_id'), ['role_id'], unique=False)

    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('invitation_template_id', sa.Integer(), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('event_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=True),
    sa.Column('end_time', sa.Time(), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('venue_name', sa.String(length=200), nullable=True),
    sa.Column('venue_address', sa.Text(), nullable=True),
    sa.Column('latitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('longitude', sa.Numeric(precision=9, scale=6), nullable=True),
    sa.Column('cover_image', sa.String(length=255), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('contact_name', sa.String(length=150), nullable=True),
    sa.Column('contact_phone', sa.String(length=30), nullable=True),
    sa.Column('dress_code', sa.String(length=150), nullable=True),
    sa.Column('invitation_message', sa.Text(), nullable=True),
    sa.Column('allow_walk_in', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invitation_template_id'], ['invitation_templates.id'], name=op.f('fk_events_invitation_template_id_invitation_templates'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], name=op.f('fk_events_organization_id_organizations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_organization_id'), ['organization_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_slug'), ['slug'], unique=True)

    op.create_table('event_staff',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_staff_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_event_staff_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'event_id', name=op.f('pk_event_staff'))
    )
    op.create_table('guests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('category', sa.String(length=30), nullable=False),
    sa.Column('company', sa.String(length=150), nullable=True),
    sa.Column('group_name', sa.String(length=100), nullable=True),
    sa.Column('guest_code', sa.String(length=50), nullable=True),
    sa.Column('invitation_code', sa.String(length=20), nullable=False),
    sa.Column('invitation_token', sa.String(length=64), nullable=False),
    sa.Column('checkin_token', sa.String(length=64), nullable=False),
    sa.Column('invitation_status', sa.String(length=20), server_default='draft', nullable=False),
    sa.Column('max_guest_count', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('token_regenerated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_guests_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_guests'))
    )
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_guests_checkin_token'), ['checkin_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_guests_event_id'), ['event_id'], unique=False)
        batch_op.create_index('ix_guests_event_id_name', ['event_id', 'name'], unique=False)
        batch_op.create_index(batch_op.f('ix_guests_invitation_code'), ['invitation_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_guests_invitation_token'), ['invitation_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_guests_phone'), ['phone'], unique=False)

    op.create_table('checkins',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('checked_in_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('checked_in_by', sa.Integer(), nullable=True),
    sa.Column('device_info', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['checked_in_by'], ['users.id'], name=op.f('fk_checkins_checked_in_by_users'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_checkins_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_checkins_guest_id_guests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_checkins'))
    )
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_checkins_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_checkins_guest_id'), ['guest_id'], unique=True)

    op.create_table('rsvps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('guest_id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('guest_count', sa.Integer(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('guest_count >= 0', name=op.f('ck_rsvps_guest_count_non_negative')),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_rsvps_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['guest_id'], ['guests.id'], name=op.f('fk_rsvps_guest_id_guests'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_rsvps'))
    )
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_rsvps_event_id'), ['event_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_rsvps_guest_id'), ['guest_id'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('rsvps', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_rsvps_guest_id'))
        batch_op.drop_index(batch_op.f('ix_rsvps_event_id'))

    op.drop_table('rsvps')
    with op.batch_alter_table('checkins', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_checkins_guest_id'))
        batch_op.drop_index(batch_op.f('ix_checkins_event_id'))

    op.drop_table('checkins')
    with op.batch_alter_table('guests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_guests_phone'))
        batch_op.drop_index(batch_op.f('ix_guests_invitation_token'))
        batch_op.drop_index(batch_op.f('ix_guests_invitation_code'))
        batch_op.drop_index('ix_guests_event_id_name')
        batch_op.drop_index(batch_op.f('ix_guests_event_id'))
        batch_op.drop_index(batch_op.f('ix_guests_checkin_token'))

    op.drop_table('guests')
    op.drop_table('event_staff')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_events_slug'))
        batch_op.drop_index(batch_op.f('ix_events_organization_id'))

    op.drop_table('events')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_role_id'))
        batch_op.drop_index(batch_op.f('ix_users_organization_id'))

    op.drop_table('users')
    op.drop_table('role_permissions')
    with op.batch_alter_table('invitation_templates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invitation_templates_organization_id'))

    op.drop_table('invitation_templates')
    op.drop_table('roles')
    op.drop_table('permissions')
    op.drop_table('organizations')
    # ### end Alembic commands ###
